### PR TITLE
Fix issue where no parsererror is returned on invalid XML

### LINKED ISSUE #54: Fake XHR XML document parser fails to parse.
It looks like there is an error attempting to determine what a parse error may look like. 

https://github.com/sinonjs/nise/blob/master/lib/fake-xhr/index.js#L345

I have a situation running with a DOMParser stub in node where the document `INVALID` does not return any elements with a parseerror tag name. In this situation my XML is failing to parse even though my XML is valid. The check for `getElementsByTagName("parsererror")` should verify that it got a result prior to checking the item at index 0. In my situation I have valid XML but no `parsererror` for the "INVALID" document.

### PR DESCRIPTION
**Pull request by m90**
This fixes #54 but would introduce the situation where using slightly broken DOMParsers like `xmldom` would make this test: https://github.com/sinonjs/nise/blob/929b9fe66b0c457b43094b99a8922c4928080be0/lib/fake-xhr/index.test.js#L1700-L1708 fail as it would return a document instead of `null`.

### CODE REVIEW

**Comment by fatso83** [comment]
Thank you!

File: lib/fake-xhr/index.js [hunk 1]
```diff
@@ -342,8 +342,11 @@ FakeXMLHttpRequest.parseXML = function parseXML(text) {
         try {
             if (typeof DOMParser !== "undefined") {
                 var parser = new DOMParser();
-                var parsererrorNS = parser.parseFromString("INVALID", "text/xml")
-                    .getElementsByTagName("parsererror")[0].namespaceURI;
+                var parsererrors = parser
+                    .parseFromString("INVALID", "text/xml")
```
Comment (senaev) [inline lib/fake-xhr/index.js]: there is an error
https://github.com/sinonjs/nise/issues/57
